print (input("Enter a name: ") + " was walking down the road.")
print ("When suddenly a " + input("Enter an Adjective: ") + (" ") + input("Enter a noun: ") + " attacked them.")
print ("They try to fight it off with their " + input("Enter a noun: ") + ", but fail.")
print ("They get scared and start " + input("Enter a verb: ") + ".")
print ("You are almost caught when " + input("Enter a person: ") + " saves you while driving a " + input("Enter a noun: ") + ".")
print ("Then they are brought home and start " + input("Enter a verb: ") + " toward their very " + input("Enter an Adjective: ") + " home.")
print ("Once inside they start eating a " + input("Enter an Adjective: ") + " looking " + input("Enter a Food: ") + ".")
print ("The food was so " + input("Enter an Adjective: ") + " it made the problems from that day disappear. THE END")